### PR TITLE
Add monochrome icon

### PR DESCRIPTION
**Pull request by GitGitro**
- [x] Read and followed the [contribution guidelines](https://github.com/niedev/RTranslator/blob/v2.00/CONTRIBUTING.md)

### Summary

Hi!
I've implemented the icon requested in #47, hope it's ok!

### Details

Final result:
image

### Other

_Inser here other information if you want, in any way you like (otherwise delete this section)_

### CODE REVIEW

**Review by niedev — CHANGES_REQUESTED** [review]
Hi, thank you for wanting to contribute! 

However, the icon should be identical to the previous one (excluding the support of the material you theme).

Your version:
Screenshot_20240702_232614_One UI Home

The previous one:
Screenshot_20240702_232819_One UI Home

**Comment by GitGitro** [comment]
Sure thing, but to do that i need the padding between the text and the border used in your icon, because i can't work very well on inkscape from a [png](https://github.com/niedev/RTranslator/blob/v2.00/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png).

Also if you can tell me the font you've use i can replicate the icon at the fullest extent

**Comment by niedev** [comment]
Sure, I'll send you everything tomorrow (it's midnight here and I have to reinstall Photoshop to give you this infos), thank you!

**Review by niedev — APPROVED** [review]

**Comment by niedev** [comment]
Before I used the full icon as foreground, so it was difficult to tell you the margin, so I made the necessary changes myself, now I will merge, thanks!

**Comment by GitGitro** [comment]
Great! Thank you

**Pull request merged**
