### PR TITLE
add translate for notification

### PR DESCRIPTION
**Pull request by Replica0110**
add translate for the notification

### CODE REVIEW

**Review by niedev — CHANGES_REQUESTED** [review]
Hi, thank you!

The only things to change are the notification titles, they should be the translation of "Conversation" and "WalkieTalkie" (like in the English version), not "Conversation mode" and "WalkieTalkie mode", the rest is perfect, good job!

**Comment by Replica0110** [comment]
So sorry for the mistake!
I have corrected the English translation.

**Comment by niedev** [comment]
Don't worry, but you didn't send any commit, so the pull request hasn't been modified, if you want you can write in a comment here the simplified and traditional Chinese translations of "Conversation" and "WalkieTalkie" and I'll make the changes to the pull request 👍🏻.

**Comment by Replica0110** [comment]
ok,here are the translations

in simplified Chinese:
Conversation--->对话模式
Conversation mode is running...-->对话模式正在运行...
WalkieTalkie-->对讲机模式
WalkieTalkie mode is running...-->对讲机模式正在运行...

in traditional Chinese:
Conversation--->對話模式
Conversation mode is running...-->對話模式正在運行…
WalkieTalkie-->對講機模式
WalkieTalkie mode is running...-->對講機模式正在運行…

simplified Chinese code:
`
<string name="conversation_mode" >对话模式</string>
<string name="conversation_mode_running" >对话模式正在运行…</string>
<string name="walkietalkie_mode" >对讲机模式</string>
<string name="walkietalkie_mode_running" >对讲机模式正在运行…</string>`



traditional Chinese code:
`
<string name="conversation_mode" >對話模式</string>
<string name="conversation_mode_running" >對話模式正在運行…</string>
<string name="walkietalkie_mode" >對講機模式</string>
<string name="walkietalkie_mode_running" >對講機模式正在運行…</string>
`

**Comment by niedev** [comment]
No, I need the translations for only the word "Conversation" and for the word "WalkieTalkie".

You just sent me the translations of "Conversation mode" and "WalkieTalkie mode", please remove the "mode" in the translations, that's it.

**Comment by Replica0110** [comment]
If you want the translations of the key word "Conversation" and  the key word "WalkieTalkie" like this`<string name="conversation" >对话模式</string>`. it will be duplicated with the existing code, but in Chinese, we usually add the word "mode" after it, so I have to use a different key.

If you hope me to delete the word "模式" in Chinese, here are the code:

simplified Chinese code:
`
<string name="conversation_mode_running" >对话模式正在运行…</string>
<string name="walkietalkie_mode_running" >对讲机模式正在运行…</string>`



traditional Chinese code:
`
<string name="conversation_mode_running" >對話模式正在運行…</string>
<string name="walkietalkie_mode_running" >對講機模式正在運行…</string>
`
If I misunderstood your meaning, I will close this pull request. Please forgive my poor English as well.Thank you for your patience

**Review by niedev — APPROVED** [review]
Don't worry, there's no need to close the pull request, I found the translations, and I made the changes (I just wanted to change the titles of the notifications, not their description, to understand better take a look at the commit, I directly inserted the reference to the translations already present), thank you!

**Comment by Replica0110** [comment]
@niedev Thanks again for your patience! I am still learning java, and I am not very familiar with the naming conventions, thank you very much for your correction!

**Comment by Agiens02** [comment]
@niedev 
The title in all strings.xml seems to still be xxx_mode, do I need to change it and open a new pull request? Or will you fix them?

**Comment by niedev** [comment]
Don't worry, I used other string resources for the notification titles, the xxx_mode resources can be left like this.

**Pull request merged**
